/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{html,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#ddd9d4",
        "on-error": "#ffffff",
        "surface-bright": "#fdf9f3",
        "surface-container-highest": "#e6e2dd",
        "primary": "#511a22",
        "primary-container": "#6d3037",
        "on-primary": "#ffffff",
        "on-primary-container": "#ed9aa0",
        "secondary": "#5d6046",
        "secondary-container": "#e0e2c1",
        "on-secondary-container": "#62654a",
        "tertiary": "#00351a",
        "tertiary-container": "#0f4d2c",
        "on-tertiary-container": "#81bd93",
        "surface": "#fdf9f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3ee",
        "surface-container": "#f2ede8",
        "surface-container-high": "#ece7e2",
        "on-surface": "#1c1c19",
        "on-surface-variant": "#534344",
        "outline": "#857373",
        "outline-variant": "#d8c1c2",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      spacing: {
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "margin-mobile": "1.25rem",
        "margin": "3.5rem",
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem",
        "space-lg": "2.25rem",
        "space-xl": "3.5rem",
      },
      fontFamily: {
        "body-sm": ["DM Sans"],
        "body-md": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "label-sm": ["DM Sans"],
        "label-lg": ["DM Sans"],
        "headline-sm": ["EB Garamond"],
        "headline-md": ["EB Garamond"],
        "headline-lg": ["EB Garamond"],
        "headline-lg-mobile": ["EB Garamond"],
        "display-hero": ["EB Garamond"],
        "display-hero-mobile": ["EB Garamond"],
        "subheading": ["EB Garamond"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "subheading": ["19px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
